version: '3.5'

services:
  app:
    hostname: grpc-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6565:6565"
      - "8080:8080"
      - "8000:8000"
      - "5006:5006"
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - AB_BASE_URL=${AB_BASE_URL}
      - AB_CLIENT_ID=${AB_CLIENT_ID}
      - AB_CLIENT_SECRET=${AB_CLIENT_SECRET}
      - AB_NAMESPACE=${AB_NAMESPACE}
      - PLUGIN_GRPC_SERVER_AUTH_ENABLED=${PLUGIN_GRPC_SERVER_AUTH_ENABLED}
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://otel-collector:9411/api/v2/spans
      - OTEL_TRACES_EXPORTER=zipkin
      - OTEL_METRICS_EXPORTER=none
      - OTEL_SERVICE_NAME=ExtendServiceExtensionJavaServerDocker
      - OTEL_PROPAGATORS=b3multi
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006
    logging:
      driver: loki
      options:
        loki-url: http://172.18.0.5:3100/loki/api/v1/push
        loki-external-labels: "service_name=ExtendServiceExtensionJavaServerDocker,container_name={{.Name}}"
        mode: non-blocking
        max-buffer-size: 4m
        loki-retries: "3"

networks:
  default:
    external:
      name: kafka-network
